# Generated by Django 3.1.2 on 2020-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201018_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='assets/productimages/%Y/%m/%d'),
        ),
    ]
