# Generated by Django 3.1.2 on 2020-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201018_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True),
        ),
    ]
